[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run app.py --server.port $PORT --server.headless true --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false --server.enableWebsocketCompression false"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
